"""Registro e inventario inicial"""

import sqlalchemy as sa
from alembic import op

revision = "041a7f3c068c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hosts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("mac_address", sa.String(length=17), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("hostname", sa.String(length=253), nullable=False),
        sa.Column("os_name", sa.String(length=200), nullable=False),
        sa.Column("last_inventory_at", sa.DateTime(), nullable=True),
        sa.Column("token_hash", sa.String(length=64), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mac_address"),
    )
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_login_attempts_address_hash"), ["address_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_login_attempts_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "inventory_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("host_id", sa.String(length=36), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["host_id"], ["hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host_id", "report_id", name="uq_host_report"),
    )
    with op.batch_alter_table("inventory_reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_inventory_reports_host_id"), ["host_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_inventory_reports_received_at"), ["received_at"], unique=False
        )

    op.create_table(
        "login_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("login_sessions")
    with op.batch_alter_table("inventory_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_reports_received_at"))
        batch_op.drop_index(batch_op.f("ix_inventory_reports_host_id"))

    op.drop_table("inventory_reports")
    op.drop_table("users")
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_login_attempts_created_at"))
        batch_op.drop_index(batch_op.f("ix_login_attempts_address_hash"))

    op.drop_table("login_attempts")
    op.drop_table("hosts")
    # ### end Alembic commands ###
